version: "3.1"
services:
  node:
    container_name: "app_name"
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules